### ISSUE TITLE
arm/aarch64 version of infernal

### ISSUE THREAD

**Issue by Bicyclecardcn** [EddyRivasLab/infernal#30] opened 2022-01-31 23:35 UTC
Hi，
I am now working on arm/aarch64 linux server. I'm wordering if there is any arm/aarch64 version of infernal. 
Or there is a compile guide for this version.

Thanks.

**Comment by npcarter** [comment] 2022-01-31 23:39
Hello.  We haven't looked at an ARM version of Infernal, but my
understanding is that the SIMD code that can't just be compiled for a new
architecture is all in HMMER.  We have an ARM version of HMMER that is
fully functional and will be released soon.  If you wanted to experiment,
you could check out the h3-arm branch of HMMER from our Github repo (which
requires the develop branch of Easel), build that, and see if Infernal
compiles when that version of HMMER is used.

-Nick

**Comment by Bicyclecardcn** [comment] 2022-02-01 00:11
I see what you mean. 
Actually, I've already built HMMER on my serve. When I try build infernal, the first problem is that configure seems automatically check the version.
Here is the output of "./configure":

configure: Configuring Infernal for your system.
checking build system type... aarch64-unknown-linux-gnu
checking host system type... aarch64-unknown-linux-gnu
checking whether to compile using MPI... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for gcc option to accept ISO C99... none needed
checking for gcc option to accept ISO Standard C... (cached) none needed
checking how to run the C preprocessor... gcc -E
checking for a BSD-compatible install... /usr/bin/install -c
checking for ranlib... ranlib
checking for ar... /usr/bin/ar
checking whether ln -s works... yes
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking whether gcc is Clang... no
checking whether pthreads work with "-pthread" and "-lpthread"... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking whether gcc can compile our Altivec/VMX code... no
checking whether gcc can compile our SSE code... no
configure: ::::::::::--- no vector instruction set ---::::::::::
configure: Infernal requires SSE or VMX vector instructions.
configure: Supported platforms are x86 (Intel/AMD) and PowerPC.
configure: error: No supported vectorization found for your machine.

How to handle this?

**Comment by npcarter** [comment] 2022-02-01 00:43
Ah, I see.  What's going on there is that Infernal's configure script is
trying to gather the information necessary to configure Infernal, HMMER,
and Easel, so it needs to know about the processor's SIMD instructions.
Because we haven't updated Infernal's configure script to know about ARM
neon, it can't find a valid SIMD ISA and crashes.

I don't normally work on Infernal, but I can talk to the person who does
and see how they feel about doing an ARM version.  It should be a pretty
quick port.

-Nick

**Comment by Bicyclecardcn** [comment] 2022-02-01 03:33
Waiting for reply.
Appreciated.

**Comment by npcarter** [comment] 2022-03-04 23:42
Update: We now have an ARM version of Infernal in the h3-arm branch of the
Github.  It has only been very lightly tested, but passes the basic tests.
(Our local Infernal expert has been out sick)

-Nick

**Comment by cossio** [comment] 2022-09-29 00:16
+1 Any updates? Thanks.

**Comment by npcarter** [comment] 2022-09-29 18:19
Status on this is unchanged -- the version of Infernal in the h3-arm branch
passes the small number of tests that we've thrown at it.  Have you tried
that version and had problems?  If you (or someone else) were willing to do
some Infernal runs on M1 and compare the results to x86, that'd be a big
help to us.  The problem we're having here is that the Infernal developer
doesn't have access to an M1 mac, so it's tough for him to do much.

That said, all of the ARM-specific code in Infernal is taken from HMMER,
which we have tested more on M1, and works well, so we're fairly confident
in the port.  I don't have a date on when we'll do an official release of
the M1 versions of HMMER and Infernal, but the number of things that happen
first has gone down a great deal recently.

-Nick

**Comment by nawrockie** [comment] 2022-10-11 18:41
The `develop` branch of infernal should now build on arm/aarch64, by following directions here:
https://github.com/EddyRivasLab/infernal/wiki#initial-checkout

But checking out the `develop` branch of infernal, hmmer and easel. To successfully build as of now, you'll also have to comment out the 4 lines with `profmark` in them in the `hmmer/Makefile.in` file prior to running `configure`. 

I've deleted the `h3-arm` branch because it is fully merged with `develop`.

**Comment by nawrockie** [comment] 2023-06-29 14:39
Updated instructions for building the develop branch of infernal (disregard instructions above from Oct 11, 2022):
```   
$ git clone https://github.com/EddyRivasLab/infernal
$ cd infernal
$ git checkout develop
$ git clone https://github.com/EddyRivasLab/hmmer
$ (cd hmmer; git checkout develop)
$ git clone https://github.com/EddyRivasLab/easel
$ (cd easel; git checkout develop)
$ autoconf
$ ./configure; make;
```

**Comment by AntonPetrov** [comment] 2023-07-04 12:10
Thank you for the updated instructions @nawrockie!

I can confirm that this works on an M2 laptop. Here is a working Dockerfile snippet in case it's useful for anyone else (including installing easel mini apps):

```Dockerfile
FROM python:3

RUN \
    git clone https://github.com/EddyRivasLab/infernal && \
    cd infernal && \
    git checkout develop && \
    git clone https://github.com/EddyRivasLab/hmmer && \
    (cd hmmer; git checkout develop) && \
    git clone https://github.com/EddyRivasLab/easel && \
    (cd easel; git checkout develop) && \
    autoconf && \
    ./configure; make; make install && \
    (cd easel && make install) && \
    cd .. && rm -rf infernal
```

I would like to note that these steps seem to require `autoconf >= 2.71`, so the above instructions won't work on some older base images, like `gcc:11`, without doing the following first:

```Dockerfile
RUN \
    wget http://ftp.gnu.org/gnu/autoconf/autoconf-2.71.tar.gz && \
    tar xzvf autoconf-2.71.tar.gz && \
    cd autoconf-2.71 && \
    ./configure && \
    make && \
    make install
```

Thanks again and it's great to see Infernal running nicely on Apple silicon 🚀

**Comment by cjw85** [comment] 2023-08-02 14:48
I just stumbled on this thread after spending an afternoon reworking the v1.1.4 release to work on aarch64! 🤦 

@nawrockie Do you have an idea when you might make a new release?

**Comment by npcarter** [comment] 2023-08-02 17:13
Hello,

The ARM-compatible version of Infernal is currently bottlenecked by getting the next release of HMMER out, as HMMER is where the ARM-specific code is located.  Unfortunately, I don’t have a good date for you on when the HMMER release will be.  Sean has been working on it, and we hope to do it soon, but I can’t give you a date.

-NIck

**Comment by gaboentropy** [comment] 2023-08-26 16:37
hmmer 3.4 is now released, and it does compile for M1 macs. So, maybe infernal's next?

**Comment by npcarter** [comment] 2023-08-26 18:32
Yes. Eric Nawrocki, who maintains Infernal, is working on a release now.

-Nick

**Comment by nawrockie** [comment] 2023-09-21 15:59
The v1.1.5 release is out and builds on arm/aarch64.

**Closed as completed by nawrockie** 2023-09-21 15:59 UTC
