### ISSUE TITLE
Searching the Rfam CM database with a query sequence fails

### ISSUE THREAD

**Issue by bifxcore** [EddyRivasLab/infernal#17] opened 2019-07-26 22:59 UTC
Attempting to run cmscan locally:
- infernal is already installed by our IT folks as part of https://www.l7informatics.com/resources/biobuilds-2017-11/
- downloaded ftp://ftp.ebi.ac.uk/pub/databases/Rfam/12.1/Rfam.cm.gz
- I was unable to find the source code on our local system, so I downloaded https://github.com/EddyRivasLab/infernal/tree/master/testsuite/Rfam.12.1.clanin

Followed instructions as described on p27 of http://eddylab.org/infernal/Userguide.pdf and cmscan fails with error:
FAIL: Error: unable to find model RyeB listed in Rfam.12.1.clanin in SSI index file

I just deleted RyeB from the Rfam.12.1.clanin file and it appears to run.

**Comment by nawrockie** [comment] 2019-08-02 17:02
Hi bifxcore,

I am unable to reproduce your problem. Can you please confirm that there is a line: 
`Name    RyeB`
in your Rfam.cm file (actually there should be two such lines)? 

If so, I think that the problem might be that you have a file `Rfam.cm.ssi` in the directory you are running `cmscan` from and that this `Rfam.cm.ssi` was created by `cmpress` call on a different file called `Rfam.cm`. That is not the Rfam 12.1 Rfam.cm file downloaded and gunzipped from EBI ftp.  You should be able to tell from the file time stamps. The fix for this is to delete all files that match `Rfam.cm.*` in the current directory and rerun `cmpress` on `Rfam.cm`. 

If you don't have any `Name  RyeB` lines in your Rfam.cm file, then I think you are not using the Rfam 12.1 `Rfam.cm` file.

**Comment by bifxcore** [comment] 2019-08-02 17:19
Thanks for troubleshooting.

My Rfam.cm does not have any Name RyeB line.

```
$> grep RyeB Rfam.cm
NAME     SdsR_RyeB
DESC     SdsR_RyeB RNA
NAME  SdsR_RyeB
DESC     SdsR_RyeB RNA
```

In any case, I got it to work by modifying the Rfam.12.1.clanin file:
```
$> diff Rfam.12.1.clanin_ORIG Rfam.12.1.clanin
99c99
< CL00105 SraC_RyeA RyeB
---
> CL00105 SraC_RyeA
```

**Comment by nawrockie** [comment] 2019-08-02 18:28
No problem. I'm glad you got it to work, but I think this means your Rfam.cm isn't from release 12.1:

```
$ wget ftp://ftp.ebi.ac.uk/pub/databases/Rfam/12.1/Rfam.cm.gz
$ gunzip Rfam.cm.gz
$ grep RyeB Rfam.cm
NAME     RyeB
NAME  RyeB
```

I'll close the issue now, please reopen if you have further questions.

**Closed as completed by nawrockie** 2019-08-02 18:28 UTC
